train:
  lr: 1e-5
  warmup_steps: 30
  metrics:
    - MeanIoU
  losses:
    - CELoss
    - DiceLoss
  loss_weights:
    - 0.5
    - 0.5
  loss_mode: binary
  device: 0

data:
  train_data: ../data/datasets/human-seg-of
  val_data: ../data/datasets/human-seg-of
  train_bs: 1
  val_bs: 1
  train_workers: 0
  val_workers: 0