logging:
  exp_name: human_seg_v1.01
  project_name: segm-pro
  log_every_n_steps: 50
  default_root_dir: ../data/checkpoints
  best_metric: MeanIoU

train:
  epochs: 100
  lr: 1e-5
  warmup_steps: 100
  metrics:
    - MeanIoU
  losses:
    - CELoss
    - JaccardLoss
  loss_weights:
    - 0.5
    - 0.5
  loss_mode: binary
  acc_grad_batches: 2
  gradient_clip_val: 0.5
  device: 0
  n_debug_images: 5

data:
  train_data: ../data/datasets/human-seg/train
  val_data: ../data/datasets/human-seg/val
  train_bs: 3
  val_bs: 3
  train_workers: 8
  val_workers: 8